### ISSUE TITLE
Migrate to kotlinx.io for efficient processing of contiguious bytes

### ISSUE THREAD

**Issue by JesusMcCloud** [a-sit-plus/signum#120]
we already have it as a transitive dependency from kotlinx.serialzation, so we should really adopt it and ditch bytearrays as underlying data structure. especially DER-encoding CONSTRUCTED ASN.1 elements is a mess performance-wise

**Comment by JesusMcCloud** [comment]
see #168

**Comment by iaik-jheher** [comment]
is this closed by #168?
