### ISSUE TITLE
Provide default arguments for `Asn1TreeBuilder.() -> Unit`

### ISSUE THREAD

**Issue by ShiinaSekiu** [a-sit-plus/signum#145]
In some practices we may not use the child node builder.
```
Asn1.ExplicitlyTagged(34U) { }
```
https://github.com/a-sit-plus/signum/blob/e8f9bd4a0be5a9018e6e4ffe137b22191b06c1e1/indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/encoding/Asn1Encoding.kt#L191
Maybe it should be changed to?
```
fun ExplicitlyTagged(tag: ULong, root: Asn1TreeBuilder.() -> Unit = { }): Asn1ExplicitlyTagged {
```

**Comment by JesusMcCloud** [comment]
Personally, I think the intentions are clearer, if the empty lambda needs to be spelled out. After all you are creating an empty structure. Therefore, I think the code should clearly mirror this intent.

**Comment by JesusMcCloud** [comment]
@ShiinaSekiu feel free to reopen, if you can present a legit use case
