### ISSUE TITLE
[Supreme] Decrease minSDK from 30 to 29 for android

### ISSUE THREAD

**Issue by WebTiger89** [a-sit-plus/signum#161]
Is it possible to decrease the min supported SDK for android? I want to do signature verification with SHA256 and RSA, maybe I can omit supreme module?

**Comment by JesusMcCloud** [comment]
the verifier is part of the supreme module. how low would you want the minSDK to be? we might be able to lower it, but onyl if working with biometrics does not turn into a hot mess

**Comment by JesusMcCloud** [comment]
@FelixHoer would [this part of the code](https://github.com/a-sit-plus/signum/blob/e8f9bd4a0be5a9018e6e4ffe137b22191b06c1e1/supreme/src/androidMain/kotlin/at/asitplus/signum/supreme/os/AndroidKeyStoreProvider.kt#L193C1-L209C18) still work with SDK 29?

**Comment by JesusMcCloud** [comment]
We've looked into this. The issue with decreasing the minSDK is that the constraints on the key cannot be as granular as we have it now. This is irrelevant for verification, though.
As we're hamstrung by Kotlin/Native limitations related to how modules depend on each other, we need to figure out, if and how we want to separate verification from signing.

**Comment by JesusMcCloud** [comment]
closing in favour of #190
