### ISSUE TITLE
Optimize library size

### ISSUE THREAD

**Issue by CoreFloDev** [a-sit-plus/signum#173]
Hi,

I have noticed that on android it ship with multiples files that aren't accessible:
org/bouncycastle/pqc/crypto/picnic/lowmcL5.bin.properties
org/bouncycastle/pqc/crypto/picnic/lowmcL3.bin.properties
org/bouncycastle/pqc/crypto/picnic/lowmcL1.bin.properties
org/bouncycastle/x509/CertPathReviewerMessages_de.properties
org/bouncycastle/x509/CertPathReviewerMessages.properties
org/bouncycastle/pkix/CertPathReviewerMessages_de.properties
org/bouncycastle/pkix/CertPathReviewerMessages.properties

Those files adds a total of 1.2MB to the apk size and aren't accessible to the android application, would it be possible to remove those files from the library ?

Thanks

**Comment by JesusMcCloud** [comment]
Thanks for the report!

Am I correct that this is simply a `resource.excludes.add` for each of these?

**Comment by CoreFloDev** [comment]
That's what I use on my end yes
